language: python
python:
  - "2.7"
  - "3.4"
  - "2.6"
  - "3.3"
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - 'pip install -e ".[test]"'
    - 'pip install coveralls'
script:
    - "python ./setup.py test"
after_success:
    - coveralls
